### ISSUE TITLE
Twice inject for a 32 bit process in 64-bit system

### ISSUE THREAD

**Issue by mixree** [dennisbabkin/InjectAll#6] opened 2024-11-29 11:35 UTC
I'm a new to github and I don't know how to modify code directly, and I love this project.

In DrvMain.cpp, I change the OnLoadImage() method. Here are part code:

```
#ifdef _WIN64
			BOOLEAN bWowProc = IoIs32bitProcess(NULL);
			if (!bWowProc)
			{
				status = sec.GetSection(&pDS);
				InjectSection(sec, status, ProcessId, pDS);  // New method
			}
			else
			{
				status = secWow.GetSection(&pDS);
				InjectSection(secWow, status, ProcessId, pDS); // New method
			}
#else
			BOOLEAN bWowProc = FALSE;
			status = sec.GetSection(&pDS);
			InjectSection(sec, status, ProcessId, pDS);
#endif
```

And, here is new Method InjectSection():
```
VOID InjectSection(CSection section, NTSTATUS status, HANDLE ProcessId, DLL_STATS* pDS)
{
	UNREFERENCED_PARAMETER(section);
	UNREFERENCED_PARAMETER(status);
	UNREFERENCED_PARAMETER(ProcessId);
	UNREFERENCED_PARAMETER(pDS);

	if (NT_SUCCESS(status))
	{
		status = section.InjectDLL(pDS);
		if (!NT_SUCCESS(status))
		{
			DbgPrintLine("ERROR: (0x%X) sec.InjectDLL, PID=%u", status, (ULONG)(ULONG_PTR)ProcessId);
		}
	}
	else
	{
		//Error
		DbgPrintLine("ERROR: (0x%X) GetSection, PID=%u", status, (ULONG)(ULONG_PTR)ProcessId);
	}
}
```

**Comment by dennisbabkin** [comment] 2024-12-02 20:15
This is not a bug. Closing this issue.

**Closed as not planned** 2024-12-02 20:15 UTC
